# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: selenium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  tests_e2e:
    name: Run selenium UI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
     
      - name: get selenium test repo
        run: git clone https://github.com/dawnsix/js-selenium.git
        
      - name: Create browserstack config file
        working-directory: ./js-selenium
        run: |
          working-directory: ./js-selenium
          echo ${{ secrets.BROWSERSTACK_KEY }} >> bs-template.yml
          echo ${{ secrets.BROWSERSTACK_USERNAME }} >> bs-template.yml
          mv bs-template.yml browserstack.yml
        
      - name: Set up test repo
        working-directory: ./js-selenium
        run: | 
          npm i
          
      - name: Run tests
        working-directory: ./js-selenium
        run: | 
          npm run test-bs -- -g login
